FROM hitalos/laravel:latest

WORKDIR '/var/www'

COPY . .

RUN composer install
RUN npm install

# CMD ["php" "artisan" "serve" "--host=0.0.0.0" "--port=8181"]
CMD ["php" "-S" "0.0.0.0:80" "-t" "public" "public/index.php"]
EXPOSE 8181