FROM php:7.3-apache

RUN apt-get update -y && apt-get install -y openssl zip unzip git
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo mbstring


RUN apt-get update && apt-get install -y node npm

WORKDIR '/app'

COPY . .

RUN composer install
RUN npm install

CMD ["php" "artisan" "serve" "--host=0.0.0.0" "--port=8181"]
EXPOSE 8181