# FROM php:7.3-fpm-alpine
FROM hitalos/php:latest

WORKDIR /var/www
COPY ./ ./

RUN composer update

CMD php artisan key:generate && php artisan serve --host=0.0.0.0 --port=8181
EXPOSE 8181

# HEALTHCHECK --interval=1m CMD curl -f http://localhost/ || exit 1